const GET_COUNTRIES = "GET_COUNTRIES";
const GET_COUNTRY_DETAILS = "GET_COUNTRY_DETAILS";
const SEARCH_BY_NAME = "SEARCH_BY_NAME";
const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
const FILTER_BY_ACTIVITY_NAME = "FILTER_BY_ACTIVITY_NAME";
const ORDER_BY_ALPHA_ASC = "ORDER_BY_ALPHA_ASC";
const ORDER_BY_ALPHA_DESC = "ORDER_BY_ALPHA_DESC";
const ORDER_BY_POP_ASC = "ORDER_BY_POP_ASC";
const ORDER_BY_POP_DESC = "ORDER_BY_POP_DESC";

module.exports = {
  GET_COUNTRIES,
  GET_COUNTRY_DETAILS,
  SEARCH_BY_NAME,
  FILTER_BY_CONTINENT,
  FILTER_BY_ACTIVITY_NAME,
  ORDER_BY_ALPHA_ASC,
  ORDER_BY_ALPHA_DESC,
  ORDER_BY_POP_ASC,
  ORDER_BY_POP_DESC,
};
