const GET_COUNTRIES = "GET_COUNTRIES";
const GET_COUNTRY_DETAILS = "GET_COUNTRY_DETAILS";
const SEARCH_BY_NAME = "SEARCH_BY_NAME";
const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
const FILTER_BY_ACTIVITY_NAME = "FILTER_BY_ACTIVITY_NAME";
const GET_COUNTRIES_ACTIVITIES = "GET_COUNTRIES_ACTIVITIES";
const ORDER = "ORDER";
const SET_ORDER = "SET_ORDER";
const SET_CONTINENTS_FILTER = "SET_CONTINENTS_FILTER";
const SET_COUNTRY_SEARCH = "SET_COUNTRY_SEARCH";
const SET_ACTIVITY_FILTER = "SET_ACTIVITY_FILTER";
const FILTER_COUNTRIES = "FILTER_COUNTRIES";

module.exports = {
  GET_COUNTRIES,
  GET_COUNTRY_DETAILS,
  SEARCH_BY_NAME,
  FILTER_BY_CONTINENT,
  FILTER_BY_ACTIVITY_NAME,
  GET_COUNTRIES_ACTIVITIES,
  SET_ORDER,
  ORDER,
  SET_CONTINENTS_FILTER,
  SET_COUNTRY_SEARCH,
  SET_ACTIVITY_FILTER,
  FILTER_COUNTRIES,
};
