const GET_COUNTRIES = "GET_COUNTRIES";
const GET_COUNTRY_DETAILS = "GET_COUNTRY_DETAILS";
const SEARCH_BY_NAME = "SEARCH_BY_NAME";
const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
const FILTER_BY_ACTIVITY_NAME = "FILTER_BY_ACTIVITY_NAME";
const ORDER_BY_ALPHA_ASC = "ORDER_BY_ALPHA_ASC";
const ORDER_BY_ALPHA_DESC = "ORDER_BY_ALPHA_DESC";
const ORDER_BY_POP_ASC = "ORDER_BY_POP_ASC";
const ORDER_BY_POP_DESC = "ORDER_BY_POP_DESC";
const GET_COUNTRIES_ACTIVITIES = "GET_COUNTRIES_ACTIVITIES";
const SET_ORDER = "SET_ORDER";
const SET_CONTINENTS_FILTER = "SET_CONTINENTS_FILTER";
const SET_COUNTRY_SEARCH = "SET_COUNTRY_SEARCH";
module.exports = {
  GET_COUNTRIES,
  GET_COUNTRY_DETAILS,
  SEARCH_BY_NAME,
  FILTER_BY_CONTINENT,
  FILTER_BY_ACTIVITY_NAME,
  ORDER_BY_ALPHA_ASC,
  ORDER_BY_ALPHA_DESC,
  ORDER_BY_POP_ASC,
  ORDER_BY_POP_DESC,
  GET_COUNTRIES_ACTIVITIES,
  SET_ORDER,
  SET_CONTINENTS_FILTER,
  SET_COUNTRY_SEARCH
};
