const ALPHA_ASC = 'ALPHA_ASC';
const ALPHA_DESC = 'ALPHA_DESC';
const POP_ASC = 'POP_ASC';
const POP_DESC = 'POP_DESC';
const CONTINENT_FILTER = 'CONTINENT_FILTER';
const ACTIVITY_FILTER = 'ACTIVITY_FILTER';

module.exports = {
ALPHA_ASC,
ALPHA_DESC,
POP_ASC,
POP_DESC,
CONTINENT_FILTER,
ACTIVITY_FILTER
}